file_read = open('codingal.txt','r')
print("file in read mode")
print(file_read.read())
file_read.close()
file_write = open('codingal.txt','w')
file_write.write("file in write mode")
file_write.write(" i love skating")
file_write.close()