import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
sns.set(style="ticks")
housing=pd.read_csv('test.csv')
print(housing.head()
      )
print(housing.info()
      )
sns.barplot(x=housing['Price'],y=housing['temperature'])
sns.distplot(housing['Price'])
plt.show()
sns.distplot(housing['Price'],kde=False,rug=True)
plt.show()
sns.jointplot(x=housing['Price'], y=housing['temperature'])
plt.show()
sns.jointplot(x=housing['Price'], y=housing['temperature'], kind='hex')
plt.show()
sns.jointplot(x=housing['Price'], y=housing['temperature'], kind='kde')
plt.show()
sns.pairplot(housing[['Price ', 'Population', 'Area House Age']])
plt.show()
sns.stripplot(x=housing['Price'],y=housing['Population'])
sns.stripplot(x=housing['Area House Age'],y=housing['Population'],jitter=True)
sns.swarmplot(x=housing['humidity'],y=housing['Population'])
plt.show
sns.barplot(x=housing['humidity'],y=housing['Population'],heu=housing['weather_type'])
plt.show()
sns.countplot(x=housing('Area House Age'))
plt.show()
sns.pointplot(x=housing['Price'],y=housing['Population'],heu=housing['weather_type'])
plt.show()