file = open('codingal.txt','r')
print(file.read())
file.close()
file = open('codingal.txt','r')
print('\n Read in parts \n')
print(file.read(10))
file.close()
file = open('codingal.txt','a')
file.write  ("Hi, my name is penguine. I am in grade 1")
file.close()